# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/indexer.ipynb (unless otherwise specified).

__all__ = ['create_index', 'get_knns', 'get_knn']

# Cell
import nmslib
import torch

# Cell
def create_index(a):
    # index = nmslib.init(space='angulardist')
    index = nmslib.init(space='cosinesimil')
    index.addDataPointBatch(a)
    index.createIndex()
    return index

def get_knns(index, vecs):
     return zip(*index.knnQueryBatch(vecs, k=10, num_threads=4))

def get_knn(index, vec): return index.knnQuery(vec, k=10)