# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_loader": "utils.ipynb",
         "df": "get_data.ipynb",
         "get_price_and_distance": "app.ipynb",
         "pong": "app.ipynb",
         "predict": "app.ipynb",
         "app": "app.ipynb",
         "DEVICE": "config.ipynb",
         "MODEL": "app.ipynb",
         "UPLOAD_FOLDER": "app.ipynb",
         "file_id": "app.ipynb",
         "destination": "app.ipynb",
         "nn_preds": "get_img_vecs.ipynb",
         "files": "get_img_vecs.ipynb",
         "DATA_PATH": "config.ipynb",
         "IMAGE_VECS_PATH": "config.ipynb",
         "STATIC_PATH": "config.ipynb",
         "BATCH_SIZE": "config.ipynb",
         "NUM_EPOCHS": "config.ipynb",
         "sz": "config.ipynb",
         "MEAN": "config.ipynb",
         "STD": "config.ipynb",
         "ImageDataset": "dataset.ipynb",
         "img_data_urls": "get_data.ipynb",
         "unique_id": "get_data.ipynb",
         "download": "get_data.ipynb",
         "download_all": "get_data.ipynb",
         "precompute_image_vectors": "get_img_vecs.ipynb",
         "lbls": "get_img_vecs.ipynb",
         "image_dl": "get_img_vecs.ipynb",
         "image_model": "get_img_vecs.ipynb",
         "preds": "get_img_vecs.ipynb",
         "create_index": "indexer.ipynb",
         "get_knns": "indexer.ipynb",
         "get_knn": "indexer.ipynb",
         "Flatten": "models.ipynb",
         "gem": "models.ipynb",
         "GeM": "models.ipynb",
         "SnapModel": "models.ipynb",
         "create_path": "utils.ipynb",
         "check_exists": "utils.ipynb",
         "download_file_from_google_drive": "utils.ipynb"}

modules = ["app.py",
           "config.py",
           "dataset/dataset.py",
           "get_data.py",
           "get_img_vecs.py",
           "utils/indexer.py",
           "models/models.py",
           "utils/utils.py"]

doc_url = "https://Tendo.github.io/snapworth/"

git_url = "https://github.com/Tendo/snapworth/tree/master/"

def custom_doc_links(name): return None
