# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['DATA_PATH', 'IMAGE_VECS_PATH', 'STATIC_PATH', 'BATCH_SIZE', 'NUM_EPOCHS', 'sz', 'MEAN', 'STD', 'DEVICE']

# Cell
import torch
import os
from pathlib import Path
from .utils import utils

# Cell

##for colab
# DATA_PATH = utils.create_path(Path('../data'))
# IMAGE_VECS_PATH = utils.create_path(Path('../image_vecs'))
# STATIC_PATH = utils.create_path(Path('../static'))

#for heroku
DATA_PATH = utils.create_path(Path('data'))
IMAGE_VECS_PATH = utils.create_path(Path('image_vecs'))
STATIC_PATH = utils.create_path(Path('static'))

BATCH_SIZE = 96
NUM_EPOCHS = 4
sz = 512
MEAN = (0.485, 0.456, 0.406)
STD = (0.229, 0.224, 0.225)
DEVICE = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')